/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve
         * @description Nome do perfil (custom URL) → SteamID64.
         *
         *     Existe porque o usuário não sabe o próprio SteamID64: ele tem o link ou o
         *     nome do perfil. Só o backend pode resolver — a chamada exige a
         *     STEAM_API_KEY, e o SPA nunca fala com a Steam.
         */
        get: operations["resolve_api_resolve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{steamid}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Profile */
        get: operations["player_profile_api_users__steamid__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{steamid}/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Games */
        get: operations["list_games_api_users__steamid__games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{steamid}/games/{appid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game Detail */
        get: operations["game_detail_api_users__steamid__games__appid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Achievement
         * @description Conquista no detalhe do jogo.
         */
        Achievement: {
            /** Apiname */
            apiname: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description?: string | null;
            /** Icon Url */
            icon_url?: string | null;
            /** Achieved */
            achieved: boolean;
            /** Unlocked At */
            unlocked_at?: string | null;
            /** Global Percent */
            global_percent?: number | null;
        };
        /**
         * Game
         * @description Jogo da biblioteca para exibição na index.
         *
         *     `percent`/`achieved_count`/`total_count` só são preenchidos com
         *     `include=achievements`; `genres`, com `include=genres`. Sem `include`, a
         *     biblioteca custa uma única chamada à Steam e esses campos vêm vazios.
         */
        Game: {
            /** Appid */
            appid: number;
            /** Name */
            name: string;
            /** Playtime Minutes */
            playtime_minutes: number;
            /** Playtime 2Weeks Minutes */
            playtime_2weeks_minutes?: number | null;
            /** Last Played At */
            last_played_at?: string | null;
            /** Icon Url */
            icon_url?: string | null;
            /** Percent */
            percent?: number | null;
            /** Achieved Count */
            achieved_count?: number | null;
            /** Total Count */
            total_count?: number | null;
            /**
             * Genres
             * @default []
             */
            genres: string[];
        };
        /**
         * GameDetail
         * @description Detalhe de um jogo: conquistas obtidas/pendentes e progresso.
         */
        GameDetail: {
            /** Appid */
            appid: number;
            /** Name */
            name: string;
            /** Supports Achievements */
            supports_achievements: boolean;
            /** Achieved Count */
            achieved_count: number;
            /** Total Count */
            total_count: number;
            /** Percent */
            percent: number;
            /** Achievements */
            achievements: components["schemas"]["Achievement"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PlayerSummary
         * @description Identidade pública do perfil. Nunca ecoa steamid nem dados sensíveis.
         *
         *     Sem steamid **de propósito**: quem chama `/profile` já o tem no path, e um
         *     modelo que o carrega acaba o espalhando por componentes que não deviam
         *     conhecê-lo. Quem *descobre* um steamid é o `ResolvedProfile`.
         */
        PlayerSummary: {
            /** Personaname */
            personaname: string;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /**
         * ResolvedProfile
         * @description Nome do perfil resolvido para SteamID64 (REQ-061).
         *
         *     O único modelo que ecoa um steamid — descobri-lo é o serviço que a rota
         *     presta. Não é vazamento: o steamid já vive na URL pública `/u/{steamid}` do
         *     SPA. O segredo é a STEAM_API_KEY, e ela nunca sai do backend.
         */
        ResolvedProfile: {
            /** Steamid */
            steamid: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resolve_api_resolve_get: {
        parameters: {
            query: {
                vanity: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_profile_api_users__steamid__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                steamid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_games_api_users__steamid__games_get: {
        parameters: {
            query?: {
                sort?: "playtime" | "name" | "percent" | "ach_count" | "last_played";
                include?: ("achievements" | "genres")[];
            };
            header?: never;
            path: {
                steamid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    game_detail_api_users__steamid__games__appid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appid: number;
                steamid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
