/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/{steamid}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Profile */
        get: operations["player_profile_api_users__steamid__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{steamid}/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Games */
        get: operations["list_games_api_users__steamid__games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{steamid}/games/{appid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game Detail */
        get: operations["game_detail_api_users__steamid__games__appid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Achievement
         * @description Conquista no detalhe do jogo.
         */
        Achievement: {
            /** Apiname */
            apiname: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description?: string | null;
            /** Icon Url */
            icon_url?: string | null;
            /** Achieved */
            achieved: boolean;
        };
        /**
         * Game
         * @description Jogo da biblioteca para exibição na index.
         *
         *     `percent`/`achieved_count`/`total_count` só são preenchidos quando a
         *     ordenação exige conquistas (sort=percent/ach_count). `genres` só é
         *     preenchido quando `group=genre`.
         */
        Game: {
            /** Appid */
            appid: number;
            /** Name */
            name: string;
            /** Playtime Minutes */
            playtime_minutes: number;
            /** Icon Url */
            icon_url?: string | null;
            /** Percent */
            percent?: number | null;
            /** Achieved Count */
            achieved_count?: number | null;
            /** Total Count */
            total_count?: number | null;
            /**
             * Genres
             * @default []
             */
            genres: string[];
        };
        /**
         * GameDetail
         * @description Detalhe de um jogo: conquistas obtidas/pendentes e progresso.
         */
        GameDetail: {
            /** Appid */
            appid: number;
            /** Name */
            name: string;
            /** Supports Achievements */
            supports_achievements: boolean;
            /** Achieved Count */
            achieved_count: number;
            /** Total Count */
            total_count: number;
            /** Percent */
            percent: number;
            /** Achievements */
            achievements: components["schemas"]["Achievement"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PlayerSummary
         * @description Identidade pública do perfil. Nunca ecoa steamid nem dados sensíveis.
         */
        PlayerSummary: {
            /** Personaname */
            personaname: string;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    player_profile_api_users__steamid__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                steamid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_games_api_users__steamid__games_get: {
        parameters: {
            query?: {
                sort?: string;
                group?: string | null;
            };
            header?: never;
            path: {
                steamid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    game_detail_api_users__steamid__games__appid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appid: number;
                steamid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
